# Deploy Sphinx.  This could be shorter, but we also do some extra
# stuff.
#
# License: CC-0.  This is the canonical location of this file, which
# you may want to link to anyway:
#   https://github.com/coderefinery/sphinx-lesson-template/blob/main/.github/workflows/sphinx.yml
#  https://raw.githubusercontent.com/coderefinery/sphinx-lesson-template/main/.github/workflows/sphinx.yml


name: sphinx
on: [push, pull_request, workflow_dispatch]

env:
  DEFAULT_BRANCH: "main"
  MAIN_BUILD_FORMAT: "html"  # or "dirhtml"
  # If these SPHINXOPTS are enabled, then be strict about the
  # builds and fail on any warnings.
  #SPHINXOPTS: "-W --keep-going -T"
  GENERATE_PDF: false         # to enable, must be 'true' lowercase
  GENERATE_SINGLEHTML: false  # to enable, must be 'true' lowercase
  PDF_FILENAME: lesson.pdf
  MULTIBRANCH: true    # to enable, must be 'true' lowercase


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run nox
        run: |
          pip install nox
          FORCE_COLOR=1 nox

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
          lfs: true

      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      # https://docs.github.com/en/actions/guides/building-and-testing-python#installing-dependencies
      # ^-- This gives info on installing dependencies with pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --group notebook .

        # Debug
      - name: Debugging information
        env:
          ref: ${{github.ref}}
          event_name: ${{github.event_name}}
          head_ref: ${{github.head_ref}}
          base_ref: ${{github.base_ref}}
        run: |
          echo "github.ref: ${ref}"
          echo "github.event_name: ${event_name}"
          echo "github.head_ref: ${head_ref}"
          echo "github.base_ref: ${base_ref}"
          echo "GENERATE_PDF: ${GENERATE_PDF}"
          echo "GENERATE_SINGLEHTML: ${GENERATE_SINGLEHTML}"
          set -x
          git rev-parse --abbrev-ref HEAD
          git branch
          git branch -a
          git remote -v
          python -V
          pip list --not-required
          pip list


      # Build
      - uses: sphinx-doc/github-problem-matcher@1f74d6599f4a5e89a20d3c99aab4e6a70f7bda0f
      - name: Build Sphinx docs (${{ env.MAIN_BUILD_FORMAT }})
        # SPHINXOPTS used via environment variables
        run: |
          make ${{ env.MAIN_BUILD_FORMAT }}

      # singlehtml
      - name: Generate singlehtml
        if: ${{ env.GENERATE_SINGLEHTML == 'true' }}
        run: |
          make singlehtml
          mv _build/singlehtml/ _build/${{ env.MAIN_BUILD_FORMAT }}/singlehtml/

      # PDF if requested
      - name: Generate PDF
        if: ${{ env.GENERATE_PDF == 'true' }}
        run: |
          pip install sphinx_pyppeteer_builder
          make pyppeteer
          mv _build/pyppeteer/*.pdf _build/${{ env.MAIN_BUILD_FORMAT }}/${{ env.PDF_FILENAME }}

      # Stage all deployed assets in _gh-pages/ for simplicity, and to
      # prepare to do a multi-branch deployment.
      - name: Copy deployment data to _gh-pages/
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run:
          rsync -a _build/${{ env.MAIN_BUILD_FORMAT }}/ _gh-pages/

      # Add the .nojekyll file
      - name: nojekyll
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          touch _gh-pages/.nojekyll
